name: java-practice
services:
  database:
    image: mysql:latest
    container_name: dev_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=p@ssw0rd
    ports:
      - "3356:3306"
    volumes:
      - ./data/db:/var/lib/mysql