spring:
  datasource:
    url: jdbc:mysql://localhost:3356/thanhnd
    username: 'root'
    password: 'p@ssw0rd'
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 100
      maximum-pool-size: 100
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
    database-platform: org.hibernate.dialect.MySQLDialect